[package]
name = "share_map"
version = "0.1.2"
edition = "2024"
description = "An immutable map designed for shared ownership"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MaxTMahem/share_map"
homepage = "https://github.com/MaxTMahem/share_map"
documentation = "https://maxmahem.github.io/share_map/"
readme = "README.md"
keywords = ["map", "thread-safe", "immutable", "frozen"]
categories = ["data-structures", "rust-patterns"]
authors = ["Austin Stanley <MaxTMahem@gmail.com>"]

[features]
serde = ["dep:serde"]

[dependencies]
frozen-collections = "0.9.1"
tap = "1.0.1"
fluent_result = { git = "https://github.com/MaxMahem/fluent_result.git" }
collect_failable = { git = "https://github.com/MaxMahem/collect_failable.git" }
thiserror = "2.0.17"
serde = { version = "1.0.228", optional = true }

[[test]]
name = "serde"
path = "tests/serde.rs"
required-features = ["serde"]

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
